import { CdkDragDrop, moveItemInArray, transferArrayItem } from '@angular/cdk/drag-drop';
import { Component, OnInit } from '@angular/core';
import { DispatcherOrderViewModel } from '../models/dispatcher-order.model';

@Component({
  selector: 'app-cdk-drag',
  templateUrl: './cdk-drag.component.html',
  styleUrls: ['./cdk-drag.component.css']
})
export class CdkDragComponent implements OnInit {
  public ordersReady = this.getReadyOrders();
  public ordersProgress = this.getProgressOrders()
  public scheduledOrders = this.getScheduledOrders()
  constructor() {
    
   }

  ngOnInit(): void {
  }

  drop(event: any) {
    console.log("order obj",event.previousContainer.data[event.previousIndex]);
    
    if (event.previousContainer === event.container) {
      console.log("sort",event.previousIndex, event.currentIndex);

      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    } else {
      transferArrayItem(
        event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex,
      );
    }
  }

  getReadyOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: " mostafa",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID:0,
        ID:3429143 ,
        TripID:1787039 ,
        Code:"B870nyZSD4" ,
        OrderNumber:"-" ,
        Name: "Eman",
        Address:"التحرير" ,
        Mobile:"0123456789" ,
        ServicesCount:0 ,
        PlannedDistance:0.6 ,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime:867 ,
        DeliveryTimeStatusName:"URGENT" ,
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus:0,
        Duration:8 ,
        Amount:0 ,
        Date: "2022-04-10T11:44:27",
        Status:2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance:0 ,
        SpentTime:1239 ,
        RateName:"NOT_RATED" ,
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID:2 ,
        IsRealTime:  false,
        IsServiceOpened:  false,
        IsTransite:  false,
        District:null ,
        SyncedTime:null,
        ShowPrint: true,
        Services: null
      },
      // {
      //   CompanyID:0,
      //   ID:3429143 ,
      //   TripID:1787039 ,
      //   Code:"B870nyZSD4" ,
      //   OrderNumber:"-" ,
      //   Name: "  eman",
      //   Address:"التحرير" ,
      //   Mobile:"0123456789" ,
      //   ServicesCount:0 ,
      //   PlannedDistance:0.6 ,
      //   PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
      //   RemainingTime:867 ,
      //   DeliveryTimeStatusName:"URGENT" ,
      //   DeliveryTimeStatus: 2,
      //   DistanceStatusName: "CLOSED_TO_BRANCH",
      //   DistanceStatus:0,
      //   Duration:8 ,
      //   Amount:0 ,
      //   Date: "2022-04-10T11:44:27",
      //   Status:2,
      //   StatusName: "On Trip",
      //   PlannedLatitude: 31.24746602321279,
      //   PlannedLongitude: 29.97743859065263,
      //   HasGoogleLocation: true,
      //   IsTopPriority: true,
      //   IsPaused: false,
      //   HasTimer: true,
      //   isSelected: false,
      //   Distance:0 ,
      //   SpentTime:1239 ,
      //   RateName:"NOT_RATED" ,
      //   Rate: 0,
      //   Note: "aaaaaaaaaaaa",
      //   OrderDeliveryTime: 30,
      //   CustomerID: 67970,
      //   Longitude: 0,
      //   Latitude: 0,
      //   BranchID:2 ,
      //   IsRealTime:  false,
      //   IsServiceOpened:  false,
      //   IsTransite:  false,
      //   District:null ,
      //   SyncedTime:null,
      //   ShowPrint: true,
      //   Services: null
      // },
    ]
  }
  getProgressOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test0",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
    ]
  }

  getScheduledOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "sara",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "Reem",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
    ]
  }

  getTrips(): any[] {
    return [
      {
        AgentCode: "130f09de-9ade-40c1-a090-4e7b1d3a096b",
        AgentID: 160,
        AgentImage: "http://scooter-api.roboost.app/uploads/agents/deliveryman_character.png",
        AgentName: "Mostafa Desoky",
        Code: "Myb0i2hivg",
        HubCode: "a3NvnYDtCb",
        HubName: "Test Hub",
        Number: "335",
        SpentTime: 1193897,
        StartTime:new Date ,
        Status: 2,
        StatusName: "Started",
        VendorCode: "ic5P06SXNGY",
        VendorName: "Roboost Vendor",
      }
    ]
  }

  

}
