import { CdkDragDrop, moveItemInArray, transferArrayItem } from '@angular/cdk/drag-drop';
import { Component, OnInit } from '@angular/core';
import { DispatcherOrderViewModel } from '../models/dispatcher-order.model';

@Component({
  selector: 'app-cdk-drag',
  templateUrl: './cdk-drag.component.html',
  styleUrls: ['./cdk-drag.component.css']
})
export class CdkDragComponent implements OnInit {
  public ordersReady = this.getReadyOrders();
  public ordersProgress = this.getProgressOrders()
  public scheduledOrders = this.getScheduledOrders()
  public trips = this.getTrips()
  constructor() {
    
   }

  ngOnInit(): void {
  }

  drop(event: any) {
    console.log("event",event);
    console.log("order obj",event.previousContainer.data[event.previousIndex]);
    
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    } else {
      transferArrayItem(
        event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex,
      );
    }
  }

  getReadyOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: " mostafa",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID:0,
        ID:3429143 ,
        TripID:1787039 ,
        Code:"B870nyZSD4" ,
        OrderNumber:"-" ,
        Name: "Eman",
        Address:"التحرير" ,
        Mobile:"0123456789" ,
        ServicesCount:0 ,
        PlannedDistance:0.6 ,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime:867 ,
        DeliveryTimeStatusName:"URGENT" ,
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus:0,
        Duration:8 ,
        Amount:0 ,
        Date: "2022-04-10T11:44:27",
        Status:2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance:0 ,
        SpentTime:1239 ,
        RateName:"NOT_RATED" ,
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID:2 ,
        IsRealTime:  false,
        IsServiceOpened:  false,
        IsTransite:  false,
        District:null ,
        SyncedTime:null,
        ShowPrint: true,
        Services: null
      },
      // {
      //   CompanyID:0,
      //   ID:3429143 ,
      //   TripID:1787039 ,
      //   Code:"B870nyZSD4" ,
      //   OrderNumber:"-" ,
      //   Name: "  eman",
      //   Address:"التحرير" ,
      //   Mobile:"0123456789" ,
      //   ServicesCount:0 ,
      //   PlannedDistance:0.6 ,
      //   PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
      //   RemainingTime:867 ,
      //   DeliveryTimeStatusName:"URGENT" ,
      //   DeliveryTimeStatus: 2,
      //   DistanceStatusName: "CLOSED_TO_BRANCH",
      //   DistanceStatus:0,
      //   Duration:8 ,
      //   Amount:0 ,
      //   Date: "2022-04-10T11:44:27",
      //   Status:2,
      //   StatusName: "On Trip",
      //   PlannedLatitude: 31.24746602321279,
      //   PlannedLongitude: 29.97743859065263,
      //   HasGoogleLocation: true,
      //   IsTopPriority: true,
      //   IsPaused: false,
      //   HasTimer: true,
      //   isSelected: false,
      //   Distance:0 ,
      //   SpentTime:1239 ,
      //   RateName:"NOT_RATED" ,
      //   Rate: 0,
      //   Note: "aaaaaaaaaaaa",
      //   OrderDeliveryTime: 30,
      //   CustomerID: 67970,
      //   Longitude: 0,
      //   Latitude: 0,
      //   BranchID:2 ,
      //   IsRealTime:  false,
      //   IsServiceOpened:  false,
      //   IsTransite:  false,
      //   District:null ,
      //   SyncedTime:null,
      //   ShowPrint: true,
      //   Services: null
      // },
    ]
  }
  getProgressOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test0",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 2,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "test",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
    ]
  }

  getScheduledOrders(): DispatcherOrderViewModel[] {
    return [
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "sara",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      {
        CompanyID: 0,
        ID: 3429143,
        TripID: 1787039,
        Code: "B870nyZSD4",
        OrderNumber: "-",
        Name: "Reem",
        Address: "التحرير",
        Mobile: "0123456789",
        ServicesCount: 0,
        PlannedDistance: 0.6,
        PlannedDeliveryTime: "2022-04-10T12:19:27.0632057",
        RemainingTime: 867,
        DeliveryTimeStatusName: "URGENT",
        DeliveryTimeStatus: 2,
        DistanceStatusName: "CLOSED_TO_BRANCH",
        DistanceStatus: 0,
        Duration: 8,
        Amount: 0,
        Date: "2022-04-10T11:44:27",
        Status: 3,
        StatusName: "On Trip",
        PlannedLatitude: 31.24746602321279,
        PlannedLongitude: 29.97743859065263,
        HasGoogleLocation: true,
        IsTopPriority: true,
        IsPaused: false,
        HasTimer: true,
        isSelected: false,
        Distance: 0,
        SpentTime: 1239,
        RateName: "NOT_RATED",
        Rate: 0,
        Note: "aaaaaaaaaaaa",
        OrderDeliveryTime: 30,
        CustomerID: 67970,
        Longitude: 0,
        Latitude: 0,
        BranchID: 2,
        IsRealTime: false,
        IsServiceOpened: false,
        IsTransite: false,
        District: null,
        SyncedTime: null,
        ShowPrint: true,
        Services: null
      },
      
    ]
  }

  getTrips(): any[] {
    return [
      {
        ArrivalTime: null,
        ArrivalTimeSecond: 0,
        BranchID: 2,
        BranchName: null,
        CloseTime: null,
        Code: "1VPkZ_i5C6",
        CreatedDate: "2022-04-11T12:47:57.918941",
        DeliverymanID: 441,
        DeliverymanImage: "https://api.tayar.app/uploads/deliverymen/598d7ba2-766f-4b7d-8dbc-cef262fc5b0f.jpg",
        DeliverymanName: "احمد محمد نصر ",
        ExcelantMaxTime: 315,
        ExpectedRateColor: "#cc324c",
        ExpectedRateName: "Too Late",
        GoodMaxTime: 375,
        ID: 1792838,
        IsPaused: false,
        IsSpecialTrip: false,
        LateMaxTime: 450,
        Number: 24341,
        Orders: [],
        Performance: {ID: 1792838, Rate: 4, StatusName: 'TOO LATE', RemainingTime: 0, Color: '#b5062b'},
        PickupTime: null,
        PlannedCompleteTime: "2022-04-11T13:57:57.8625009",
        PlannedCompleteTimeInt: -623,
        PlannedDuration: 0,
        RateStatus: 0,
        RateStatusName: "NOT_RATED",
        ServingTime: 5,
        SpentTime: 902,
        StartTime: "2022-04-11T12:49:45.3288956",
        Status: 10,
        StatusName: "Started",
      },
      {
        ArrivalTime: null,
        ArrivalTimeSecond: 0,
        BranchID: 2,
        BranchName: null,
        CloseTime: null,
        Code: "1VPkZ_i5C6",
        CreatedDate: "2022-04-11T12:47:57.918941",
        DeliverymanID: 441,
        DeliverymanImage: "https://api.tayar.app/uploads/deliverymen/598d7ba2-766f-4b7d-8dbc-cef262fc5b0f.jpg",
        DeliverymanName: "Ahmed",
        ExcelantMaxTime: 315,
        ExpectedRateColor: "#cc324c",
        ExpectedRateName: "Too Late",
        GoodMaxTime: 375,
        ID: 1792838,
        IsPaused: false,
        IsSpecialTrip: false,
        LateMaxTime: 450,
        Number: 24341,
        Orders: [],
        Performance: {ID: 1792838, Rate: 4, StatusName: 'TOO LATE', RemainingTime: 0, Color: '#b5062b'},
        PickupTime: null,
        PlannedCompleteTime: "2022-04-11T13:57:57.8625009",
        PlannedCompleteTimeInt: -623,
        PlannedDuration: 0,
        RateStatus: 0,
        RateStatusName: "NOT_RATED",
        ServingTime: 5,
        SpentTime: 902,
        StartTime: "2022-04-11T12:49:45.3288956",
        Status: 10,
        StatusName: "Started",
      },
      {
        ArrivalTime: null,
        ArrivalTimeSecond: 0,
        BranchID: 2,
        BranchName: null,
        CloseTime: null,
        Code: "1VPkZ_i5C6",
        CreatedDate: "2022-04-11T12:47:57.918941",
        DeliverymanID: 441,
        DeliverymanImage: "https://api.tayar.app/uploads/deliverymen/598d7ba2-766f-4b7d-8dbc-cef262fc5b0f.jpg",
        DeliverymanName: "Eman",
        ExcelantMaxTime: 315,
        ExpectedRateColor: "#cc324c",
        ExpectedRateName: "Too Late",
        GoodMaxTime: 375,
        ID: 5,
        IsPaused: false,
        IsSpecialTrip: false,
        LateMaxTime: 450,
        Number: 24341,
        Orders: [],
        Performance: {ID: 1792838, Rate: 4, StatusName: 'TOO LATE', RemainingTime: 0, Color: '#b5062b'},
        PickupTime: null,
        PlannedCompleteTime: "2022-04-11T13:57:57.8625009",
        PlannedCompleteTimeInt: -623,
        PlannedDuration: 0,
        RateStatus: 0,
        RateStatusName: "NOT_RATED",
        ServingTime: 5,
        SpentTime: 902,
        StartTime: "2022-04-11T12:49:45.3288956",
        Status: 10,
        StatusName: "Started",
      }
      
    ]
  }

  

}
